//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcCrud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class acc_transactions
    {
        public int trans_id { get; set; }
        public Nullable<int> category_id { get; set; }
        public string category_name { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string description { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string fiscal_year { get; set; }
        public string paymentmode { get; set; }
    }
}
